spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: smartApi
  ai:
    google:
      model:
        transcription: genai
        audio:
          speech: genai
      genai:
        chat:
          options:
            temperature: 0.8
            response-format:
              type: TEXT
        api-key: ${GENAI_KEY}
api:
  financeira:
    url:  ${API_URL}