spring:
  docker:
    compose:
      enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    port: 5432
#    username: postgres
#    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      password: minhaSenha
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  application:
    name: smartApi
  ai:
    google:
      model:
        transcription: genai
        audio:
          speech: genai
      genai:
        chat:
          options:
            temperature: 0.8
            response-format:
              type: TEXT
        api-key: ${GENAI_KEY}
api:
  scriptPath: C:/dev/backend/python/transcription/transcribe.py
  financeira:
    url:  ${FINANCE_URL}
  auth:
    url: ${AUTH_URL}
    login: login
    password: password
    system: fin